### PR TITLE
Fix issue with EthernetClient::write and large packages, closes #37

### LINKED ISSUE #37: EthernetClient::write cannot send large packages
Hi again 😃 

I'm trying to send a bit larger packages and discovered that it isn't possible with the current implementation. The EthernetClient implementation passes all calls through to LwIP but LwIP's ``tcp_write`` refuses larger packages than ``TCP_SND_BUF = 5840``. The doc for ``tcp_write`` states:

````c
 * The tcp_write() function will fail and return ERR_MEM if the length
 * of the data exceeds the current send buffer size or if the length of
 * the queue of outgoing segment is larger than the upper limit defined
 * in lwipopts.h. The number of bytes available in the output queue can
 * be retrieved with the tcp_sndbuf() function.
 *
 * The proper way to use this function is to call the function with at
 * most tcp_sndbuf() bytes of data. If the function returns ERR_MEM,
 * the application should wait until some of the currently enqueued
 * data has been successfully received by the other host and try again.
 *
````
It should be up to the caller (in this case ``EthernetClient::write``) to make multiple calls to ``tcp_write`` with the data length less than ``tcp_sndbuf()``.

Current ``tcp_write`` call in ``EthernetClient::write``
````c++
99  if(ERR_OK != tcp_write(_tcp_client->pcb, buf, size, TCP_WRITE_FLAG_COPY)) {
100    return 0;
101  }
````

I guess a simple fix for this is to loop over ``tcp_write`` and split the buffer in smaller sizes if data length is larger than ``tcp_sndbuf()``

### PR DESCRIPTION
**Pull request by ramboerik**
Fixes #37

### CODE REVIEW

**Comment by fpistm** [comment]
Thanks @ramboerik 

I will have a look on this.

File: src/EthernetClient.cpp [hunk 1]
```diff
@@ -96,17 +96,34 @@ size_t EthernetClient::write(const uint8_t *buf, size_t size) {
...
+  size_t max_send_size, bytes_to_send;
+  size_t bytes_sent = 0;
+  size_t bytes_left = size;
+  err_t res;
+
+  while(bytes_sent != size){
+    max_send_size = tcp_sndbuf(_tcp_client->pcb);
+    bytes_to_send = bytes_left > max_send_size ? max_send_size : bytes_left;
+
+    if(bytes_to_send > 0){
```
Comment (ABOSTM) [inline src/EthernetClient.cpp]: Instead of a timeout implementation, you can return 0 when bytes_to_send  == 0;
So if there is no buffer free it is up to application to manage (retransmition, ...).
for example:
add an else to 
```
if(bytes_to_send > 0) {
...
 } 
else {
  return 0;
}
```
and thus we avoid inifnite loop

**Comment by fpistm** [comment]
@gdsports, @sstaub,
as you made several contributions to this lib.
Could you give your feedback on this ?
Thanks in advance

File: src/EthernetClient.cpp (hunk 1 above)
Comment (ramboerik) [reply src/EthernetClient.cpp]: I cannot find exactly what behavior the write function should have but I interpreted it as it should block?

* The [official documentation](https://www.arduino.cc/en/Reference/ClientWrite) says it's  optional to read the number of written bytes and the only way you could ignore it would be if you knew everything was sent.
* [This MQTT](https://github.com/256dpi/arduino-mqtt/blob/master/src/MQTTClient.cpp#L75) implementation requires it to block until all is sent and it would not work if only a chunk was sent with the write call. The MQTT library could of course be broken.
* the [Arduino Ethernet shield](https://github.com/arduino-libraries/Ethernet/blob/master/src/socket.cpp#L422) documentation says 0 on failure, 1 on success but truncates the buffer if it's too large and returns the number of bytes that were sent.

It feels like this part of the Arduino isn't well documentated/specified? What to do? 

The proper solution would be to copy the behavior of [Linux' write](http://man7.org/linux/man-pages/man2/write.2.html) but that would require changes of the main Arduino code/documentation itself.

Comment (ABOSTM) [reply src/EthernetClient.cpp]: Hi @ramboerik,
Ok, that is fine for me if you keep your original proposal.
What about other remarks ?

Comment (ramboerik) [reply src/EthernetClient.cpp]: Ok, I keep the blocking behavior if no one else has any opinion.
